#pragma once
#include <string>
#include <vector>

/* Class contains and creates a table of pairs of words and costs -- sum of all moves between keys
 * on a keyboard that a grandma need to do to type a word*/
class WordsAndCostsTable {
public:
  // default constructor is not generated by compiler because we defined constructor below
  // filepath is empty when we choose to use package words as dictionary
  WordsAndCostsTable(const std::string &filepath = "");

  using table_t = std::vector<std::pair<std::string, uint64_t>>;
  const table_t &get_items() const { return table; }

private:
  void create_table(std::ifstream &file);
  uint64_t calculate_word_cost(const std::string &str);

  table_t table;
};